//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Vector2 p_default_TouchpadTouch;
        
        private static SteamVR_Action_Boolean p_default_ChangeMovementMode;
        
        private static SteamVR_Action_Boolean p_default_GrabLGrip;
        
        private static SteamVR_Action_Boolean p_default_GrabRGrip;
        
        private static SteamVR_Action_Single p_default_LSqueeze;
        
        private static SteamVR_Action_Single p_default_RSqueeze;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        private static SteamVR_Action_Vector2 p_locomotion_TouchpadTouch;
        
        private static SteamVR_Action_Boolean p_locomotion_Run;
        
        private static SteamVR_Action_Pose p_locomotion_Pose;
        
        private static SteamVR_Action_Skeleton p_locomotion_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_locomotion_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_locomotion_Squeeze;
        
        private static SteamVR_Action_Boolean p_locomotion_ChangeMovementMode;
        
        private static SteamVR_Action_Boolean p_locomotion_GrabLGrip;
        
        private static SteamVR_Action_Boolean p_locomotion_GrabRGrip;
        
        private static SteamVR_Action_Single p_locomotion_LSqueeze;
        
        private static SteamVR_Action_Single p_locomotion_RSqueeze;
        
        private static SteamVR_Action_Vibration p_locomotion_Haptic;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.p_default_TouchpadTouch.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ChangeMovementMode
        {
            get
            {
                return SteamVR_Actions.p_default_ChangeMovementMode.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabLGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabLGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabRGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabRGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single default_LSqueeze
        {
            get
            {
                return SteamVR_Actions.p_default_LSqueeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single default_RSqueeze
        {
            get
            {
                return SteamVR_Actions.p_default_RSqueeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 locomotion_TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.p_locomotion_TouchpadTouch.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean locomotion_Run
        {
            get
            {
                return SteamVR_Actions.p_locomotion_Run.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose locomotion_Pose
        {
            get
            {
                return SteamVR_Actions.p_locomotion_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton locomotion_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_locomotion_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton locomotion_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_locomotion_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single locomotion_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_locomotion_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean locomotion_ChangeMovementMode
        {
            get
            {
                return SteamVR_Actions.p_locomotion_ChangeMovementMode.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean locomotion_GrabLGrip
        {
            get
            {
                return SteamVR_Actions.p_locomotion_GrabLGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean locomotion_GrabRGrip
        {
            get
            {
                return SteamVR_Actions.p_locomotion_GrabRGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single locomotion_LSqueeze
        {
            get
            {
                return SteamVR_Actions.p_locomotion_LSqueeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single locomotion_RSqueeze
        {
            get
            {
                return SteamVR_Actions.p_locomotion_RSqueeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vibration locomotion_Haptic
        {
            get
            {
                return SteamVR_Actions.p_locomotion_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_ChangeMovementMode,
                    SteamVR_Actions.default_GrabLGrip,
                    SteamVR_Actions.default_GrabRGrip,
                    SteamVR_Actions.default_LSqueeze,
                    SteamVR_Actions.default_RSqueeze,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.locomotion_TouchpadTouch,
                    SteamVR_Actions.locomotion_Run,
                    SteamVR_Actions.locomotion_Pose,
                    SteamVR_Actions.locomotion_SkeletonLeftHand,
                    SteamVR_Actions.locomotion_SkeletonRightHand,
                    SteamVR_Actions.locomotion_Squeeze,
                    SteamVR_Actions.locomotion_ChangeMovementMode,
                    SteamVR_Actions.locomotion_GrabLGrip,
                    SteamVR_Actions.locomotion_GrabRGrip,
                    SteamVR_Actions.locomotion_LSqueeze,
                    SteamVR_Actions.locomotion_RSqueeze,
                    SteamVR_Actions.locomotion_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_ChangeMovementMode,
                    SteamVR_Actions.default_GrabLGrip,
                    SteamVR_Actions.default_GrabRGrip,
                    SteamVR_Actions.default_LSqueeze,
                    SteamVR_Actions.default_RSqueeze,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.locomotion_TouchpadTouch,
                    SteamVR_Actions.locomotion_Run,
                    SteamVR_Actions.locomotion_Pose,
                    SteamVR_Actions.locomotion_SkeletonLeftHand,
                    SteamVR_Actions.locomotion_SkeletonRightHand,
                    SteamVR_Actions.locomotion_Squeeze,
                    SteamVR_Actions.locomotion_ChangeMovementMode,
                    SteamVR_Actions.locomotion_GrabLGrip,
                    SteamVR_Actions.locomotion_GrabRGrip,
                    SteamVR_Actions.locomotion_LSqueeze,
                    SteamVR_Actions.locomotion_RSqueeze};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.locomotion_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.locomotion_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.locomotion_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_ChangeMovementMode,
                    SteamVR_Actions.default_GrabLGrip,
                    SteamVR_Actions.default_GrabRGrip,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.locomotion_Run,
                    SteamVR_Actions.locomotion_ChangeMovementMode,
                    SteamVR_Actions.locomotion_GrabLGrip,
                    SteamVR_Actions.locomotion_GrabRGrip};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_LSqueeze,
                    SteamVR_Actions.default_RSqueeze,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.locomotion_Squeeze,
                    SteamVR_Actions.locomotion_LSqueeze,
                    SteamVR_Actions.locomotion_RSqueeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.locomotion_TouchpadTouch};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.locomotion_SkeletonLeftHand,
                    SteamVR_Actions.locomotion_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TouchpadTouch,
                    SteamVR_Actions.default_ChangeMovementMode,
                    SteamVR_Actions.default_GrabLGrip,
                    SteamVR_Actions.default_GrabRGrip,
                    SteamVR_Actions.default_LSqueeze,
                    SteamVR_Actions.default_RSqueeze,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.locomotion_TouchpadTouch,
                    SteamVR_Actions.locomotion_Run,
                    SteamVR_Actions.locomotion_Squeeze,
                    SteamVR_Actions.locomotion_ChangeMovementMode,
                    SteamVR_Actions.locomotion_GrabLGrip,
                    SteamVR_Actions.locomotion_GrabRGrip,
                    SteamVR_Actions.locomotion_LSqueeze,
                    SteamVR_Actions.locomotion_RSqueeze};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_TouchpadTouch = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/TouchpadTouch")));
            SteamVR_Actions.p_default_ChangeMovementMode = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ChangeMovementMode")));
            SteamVR_Actions.p_default_GrabLGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabLGrip")));
            SteamVR_Actions.p_default_GrabRGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabRGrip")));
            SteamVR_Actions.p_default_LSqueeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/LSqueeze")));
            SteamVR_Actions.p_default_RSqueeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/RSqueeze")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
            SteamVR_Actions.p_locomotion_TouchpadTouch = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/locomotion/in/TouchpadTouch")));
            SteamVR_Actions.p_locomotion_Run = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/locomotion/in/Run")));
            SteamVR_Actions.p_locomotion_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/locomotion/in/Pose")));
            SteamVR_Actions.p_locomotion_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/locomotion/in/SkeletonLeftHand")));
            SteamVR_Actions.p_locomotion_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/locomotion/in/SkeletonRightHand")));
            SteamVR_Actions.p_locomotion_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/locomotion/in/Squeeze")));
            SteamVR_Actions.p_locomotion_ChangeMovementMode = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/locomotion/in/ChangeMovementMode")));
            SteamVR_Actions.p_locomotion_GrabLGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/locomotion/in/GrabLGrip")));
            SteamVR_Actions.p_locomotion_GrabRGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/locomotion/in/GrabRGrip")));
            SteamVR_Actions.p_locomotion_LSqueeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/locomotion/in/LSqueeze")));
            SteamVR_Actions.p_locomotion_RSqueeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/locomotion/in/RSqueeze")));
            SteamVR_Actions.p_locomotion_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/locomotion/out/Haptic")));
        }
    }
}
