//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_locomotion : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.locomotion_TouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Run
        {
            get
            {
                return SteamVR_Actions.locomotion_Run;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.locomotion_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.locomotion_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.locomotion_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.locomotion_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeMovementMode
        {
            get
            {
                return SteamVR_Actions.locomotion_ChangeMovementMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabLGrip
        {
            get
            {
                return SteamVR_Actions.locomotion_GrabLGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabRGrip
        {
            get
            {
                return SteamVR_Actions.locomotion_GrabRGrip;
            }
        }
        
        public virtual SteamVR_Action_Single LSqueeze
        {
            get
            {
                return SteamVR_Actions.locomotion_LSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Single RSqueeze
        {
            get
            {
                return SteamVR_Actions.locomotion_RSqueeze;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.locomotion_Haptic;
            }
        }
    }
}
